### ISSUE TITLE
Electronegativity and hardness values

### ISSUE THREAD

**Issue by mattwthompson** [SimonBoothroyd/nagl#38]
I'm curious what the source of values like these?

https://github.com/SimonBoothroyd/nagl/blob/a4b94673243e931414b77a8ab8a5af4dc615949c/nagl/tests/nn/test_process.py#L53-L57

I'm used to electronegative values on the order of 1, for example.

**Comment by pavankum** [comment]
Table 1 from Mike Gilson's paper has those values, https://pubs.acs.org/doi/pdf/10.1021/ci034148o

**Comment by SimonBoothroyd** [comment]
@pavankum is correct - that is the source!
