### ISSUE TITLE
openff-utilities 1.4 incompatibility

### ISSUE THREAD

**Issue by jthorton** [SimonBoothroyd/nagl#41]
[openff-utilities](https://github.com/openforcefield/openff-utilities) recently changed the name of an exception from `MissingOptionalDependency` to `MissingOptionalDependencyError ` which means nagl needs to be updated to work with the newest release.

**Comment by SimonBoothroyd** [comment]
This should be fixed in 0.0.9 which will be available on C-F in a few hours
